### ISSUE TITLE
Rename url links for services

### ISSUE THREAD

**Issue by mirelahal** [seeba-se/Seeba-Web-3.2#12]
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/85496935/177328479-c9c91cb1-b03d-48a5-9384-5ddd7f2f2d73.png">

should be http://seeba.imperea.ba/business-services/analysisanddiagnostics etc. -> apply to all services

p.s. links directing to these pages is from page Our Services where the list of each service is

**Comment by jasminseeba** [comment]
Issue resolved url structure changed.
![image](https://user-images.githubusercontent.com/92577165/185095318-97bfc185-88de-4c58-9c49-39892f692e65.png)
