### ISSUE TITLE
Link buttons to according pages - Technology services page

### ISSUE THREAD

**Issue by mirelahal** [seeba-se/Seeba-Web-3.2#14]
Innovate my business -> link to Value Proposition, Transform my product/service -> Value Proposition, Digitalise an existing product/service-> Value Proposition,  E-commerce solution -> Business Processes, Improve security -> Tools & Connectivity, Integration-> Business Processes

**Comment by jasminseeba** [comment]
Issue resolved buttons linked according to the provided instructions.

https://user-images.githubusercontent.com/92577165/184155354-3755cb36-e31c-4b74-a02d-17780d6c7d1f.mov
