### ISSUE TITLE
Careers page - Pattern on the background is missing

### ISSUE THREAD

**Issue by mirelahal** [seeba-se/Seeba-Web-3.2#16]
on the design:
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/85496935/177334887-1efde196-6d47-4198-899d-7229e824b125.png">

on staging:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/85496935/177334952-ef8733c8-98e0-4243-9218-1984ceeb8f85.png">

**Comment by jasminseeba** [comment]
All the issues were resolved.
![image](https://user-images.githubusercontent.com/92577165/184126878-3d0874dd-0241-4916-9f00-f711f0512ce9.png)
