### ISSUE TITLE
Mobile - "What is your challenge" section on Business services and Technology services pages

### ISSUE THREAD

**Issue by mirelahal** [seeba-se/Seeba-Web-3.2#18]
![Image from iOS (1)](https://user-images.githubusercontent.com/85496935/177344695-46d96c49-c1de-45b4-931c-7ab7d8eec66d.png)
![Image from iOS](https://user-images.githubusercontent.com/85496935/177344750-c250eba7-bb09-498e-b874-c7bb860aa81a.png)

**Comment by mirelahal** [comment]
it should be like on home page (first photo)

**Comment by jasminseeba** [comment]
Issue resolved flex applied.
![image](https://user-images.githubusercontent.com/92577165/184851485-f49fc873-c31d-44cc-b445-90dd0b1fc1c6.png)
