### ISSUE TITLE
Mobile - Technology services and Business services pages - text too small

### ISSUE THREAD

**Issue by mirelahal** [seeba-se/Seeba-Web-3.2#19]
I think this is a general problem, very small font on mobile

**Comment by jasminseeba** [comment]
Issue resolved new font size applied screenshot attached fir image was the original second image is the increased font size.
![image](https://user-images.githubusercontent.com/92577165/184851900-3e75ebd3-c9a9-4546-8865-ea445e6bb779.png)
![image](https://user-images.githubusercontent.com/92577165/184851935-ae0dd8d9-c360-47e2-8938-4da6260ad640.png)
