### ISSUE TITLE
Mobile - Fix text colour in footer

### ISSUE THREAD

**Issue by mirelahal** [seeba-se/Seeba-Web-3.2#22]
![Image from iOS (2)](https://user-images.githubusercontent.com/85496935/177347033-41ce60d1-30f3-43df-acac-96bdf8c8c046.png)

**Comment by jasminseeba** [comment]
Issue resolved text color adjusted.
![image](https://user-images.githubusercontent.com/92577165/185095712-bce6e49f-1ea1-4e95-9bf4-4d7f914bf223.png)
