### ISSUE TITLE
Reduce text size on Home landing page and the logos inside the boxes

### ISSUE THREAD

**Issue by mirelahal** [seeba-se/Seeba-Web-3.2#6]
on the design: 

<img width="938" alt="image" src="https://user-images.githubusercontent.com/85496935/177321868-786a4d39-d0bf-418a-b729-c5f6fab18671.png">

on staging:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/85496935/177322161-52a27f59-ad18-4bc5-af0c-c32c2e13b857.png">

**Comment by jasminseeba** [comment]
Issue resolved text size reduced and logo images in slider size limited to make sure they are all approximately the same size.
![image](https://user-images.githubusercontent.com/92577165/182869797-053de956-b4dd-48b3-b85b-a274959902c9.png)
