### ISSUE TITLE
Change image

### ISSUE THREAD

**Issue by mirelahal** [seeba-se/Seeba-Web-3.2#7]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/85496935/177322677-16d737d8-a94d-4675-a9b5-8d24e5db41f7.png">
 Replace this image with the one that is in the design

**Comment by jasminseeba** [comment]
Image set to match the image provided in the design.
![image](https://user-images.githubusercontent.com/92577165/182870193-7c475758-76b2-49a2-b88b-823561768765.png)
