### ISSUE TITLE
Link buttons to according pages - Home

### ISSUE THREAD

**Issue by mirelahal** [seeba-se/Seeba-Web-3.2#8]
Category: Business

Optimise your business model -> Workshops
Elevate your business strategy -> Business Support
Enter new markets -> Business Health Assessment
Increase market share -> Marketing assessment
Create marketing strategy -> Marketing Assessment
Identify gaps -> Business Health Assessment
Reach new goals -> Business suppory
Grow your business -> Business support
Create innovative solutions -> Workshops
Develop corporate culture -> Workshops

Category: Technology 

First rename buttons and then link to pages:

Digital transformation -> Value proposition
E-Commerce Solutions -> Business processes
Build new or upgrade your current website -> Business processes
Innovate your product or service -> Value proposition
Upgrade your security -> tools & connectivity
Implement a new software -> tools & connectivity
UI/UX Design -> Business processes

**Comment by jasminseeba** [comment]
Buttons link to the correct locations.
