### ISSUE TITLE
Link buttons to according pages - Starting / Scaling / Transforming pages

### ISSUE THREAD

**Issue by mirelahal** [seeba-se/Seeba-Web-3.2#9]
Optimise the business model -> BHA
Improve or create a product/service -> Marketing Assessment
Support for operations -> Business Support 
Elevate the strategy -> Workshops
New solutions -> BHA
Build the corporate culture -> Workshops

**Comment by mirelahal** [comment]
Same links on Business Services Page

**Comment by jasminseeba** [comment]
Issue resolved buttons are linked accordingly.
